<Project Sdk="Microsoft.NET.Sdk.Web">
    <ItemGroup>
        <ProjectReference Include="..\Database\Database.csproj"/>
        <ProjectReference Include="..\Domain\Domain.csproj"/>
        <ProjectReference Include="..\Application\Application.csproj"/>
        <ProjectReference Include="..\CrossCutting\CrossCutting.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="AutoMapper"/>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Scalar.AspNetCore"/>
    </ItemGroup>
</Project>
