version: '3'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pa$$w00rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  redis:
    image: redis:alpine
    command: redis-server --requirepass Pa$$w0rd
    ports:
      - 6379:6379