version: '3'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=SenhaComfy1234
      - ACCEPT_EULA=Y
    ports:
      - "1434:1433"
    volumes:
      - mssql:/var/opt/mssql/data

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
      
volumes:
  mssql: