<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\Domain\Domain.csproj"/>
        <ProjectReference Include="..\CrossCutting\CrossCutting.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
    </ItemGroup>
    <ItemGroup>
        <Using Include="Microsoft.EntityFrameworkCore"/>
    </ItemGroup>
</Project>
